services:

  mysql:
    image: mysql:8.0

    container_name: quantitymeasurementdb

    environment:
      environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: qm_db
      MYSQL_USER: qmuser
      MYSQL_PASSWORD: qmpassword

    volumes:
      - quantitymeasurement-dbdata:/var/lib/mysql

    networks:
      - quantitymeasurement-net

  backend:
    image: 064338743510.dkr.ecr.ap-south-1.amazonaws.com/quantity-measurement-ecr

    container_name: qm-app-backend

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    networks:
      - quantitymeasurement-net

networks:
  quantitymeasurement-net:
    driver: bridge

volumes:
  quantitymeasurement-dbdata:
